### PR TITLE
[WIP] Address inconsistent text box fields

### PR DESCRIPTION
**Pull request by amyrlam**
## Description of the change

_To be edited, will add "WIP comments" as a comment._

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

https://github.com/Recidiviz/covid19-dashboard/issues/196

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by amyrlam** [comment]
inputtext

@jessex @szhu question for standup as didn't quite finish yet, thought draft pr would be the best way to ask

i'm proposing that we get rid of the edit function in the right hand side facility row, seems somewhat confusing UX (but maybe there is some need there, I don't know about). then all facility edits would happen on the /facility route with a "save"

- would need to adjust styling in the facility row textarea so get cursor: pointer
- could get rid of textarea and just be text, but I think it was a textarea to address the overflow. we could address that in other ways but unclear if NVA given time constraints

after talking to sean yesterday, kind of realized that i wasn't sure why the subclick was there in the FacilityRow, when most facility stuff only persists edit on save 

//

can still do design tweaks to the input interaction, if is a good use of time
inputtext2
- removing the folder icon from the component
- size jump on edit as input is going over the folder icon
- not having the pencil there on all hover

**Comment by amyrlam** [comment]
cc @cawarren hi andrew, this is the question i mentioned at standup, lmk what you think

**Comment by jessex** [comment]
Thanks for the breakdown and screengrabs, @amyrlam!
* I would personally not be opposed to removing the facility rename functionality from the facility row if it leads to overall improved UX. I think it's a nice-to-have feature to avoid a few extra clicks in what might otherwise just be a typo fix, but I don't feel strongly about it and I somehow doubt it's a frequently used feature outside of testing. @cawarren would probably have more conviction one way or another on this one.
* If we did get rid of it, we would want to make sure that we did handle long facility names gracefully--that's worth the time spent. Some state prison names, for example, are really, really long and our userbase may be apt to use the full official names more often than not.
* I think fixing the size jump is probably most important of those three UX quirks you identified. I think having the folder icon still present regardless of whether we are currently editing the scenario name or not would be nice. But I don't have any issue with the current pencil behavior, personally. @cawarren again would have stronger conviction on these points.

**Comment by amyrlam** [comment]
thanks for chiming in. yeah i can also keep the edit in the FacilityRow, and use `InputDescription` to keep it a textarea, which is addressing overflow rn

**Comment by amyrlam** [comment]
talked to andrew
- opening a new branch now
- it may make sense to remove the folder from the component, because it will be used here https://github.com/Recidiviz/covid19-dashboard/issues/176 to open a modal

**Pull request closed without merging**
