### PR TITLE
minor ui tweaks

### PR DESCRIPTION
**Pull request by glen0071**
##  Description of the change
Wee little PR. Change body font-family, add hover underline to an a tag as directed in first couple of bullets in [document](https://docs.google.com/document/d/1OUzZnV4S9JGqUULkbTOEKUs4HTzqB73gsPuvqS2buC0/edit)

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Part of #534
Note: first PR for this issue, probably several more coming.

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jessex** [comment]
@glen0071 see the small update I made to your PR description:
1. I removed the square brackets because if they are around the issue number it means that merging the PR will not auto-close the issue, and auto-closing is the behavior we want. So we always remove the square brackets when filing the PR
2. But in this particular case, because there are multiple PRs to come for the one issue, we don't write "Closes #XXX" but "Part of #XXX"

**Comment by jessex** [comment]
Also, @glen0071, can you follow the instructions in the issue about how to update that document you drew from? There are certain conventions we follow so that other people working through the doc know what work is in progress or has already been completed. Thanks!

**Comment by glen0071** [comment]
@jessex sure. Sorry I missed that.
Not sure I understand one of the bullet points though. `File an issue in Github to track progress, referencing this issue`, Do we want to create a new issue for each bullet pointed bug I work to track progress on it as I go, and that new issue would also reference the original issue? Or is it more of a judgement call to create new issues on however many documented bugs makes sense, and just make sure nothing will get overlooked?

**Comment by jessex** [comment]
It's a judgement call, yeah. If it's something with a more significant level of effort, file an issue to track it and make sure in the _Additional Context_ field of the description template you write, "Sub-task of #534." If it's a very trivial fix, we don't need an issue, the PR can just directly reference #534.

**Comment by glen0071** [comment]
@jessex I updated the google doc per instructions on tracking those things. I didn't create a new issue b/c these seem like small fixes, and I think they're already done here. Is there more I need to do here before approval?

**Pull request merged**
