### PR TITLE
Add script to lint + add GitHub action for linting

### PR DESCRIPTION
**Pull request by szhu**
## Description of the change

- Add `yarn lint-check` to check for lint errors.
- Add `yarn lint-fix` to autofix any autofixable lint errors.
- Set up GitHub actions to run `yarn lint-check` on every push. Example:
  image

Note: The GitHub action isn't picking up line numbers from the output of `tsc`. So currently, all `tsc` annotations will appear on the top of the file where they occur.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by szhu** [comment]
I'm not sure why the GitHub action is not running. Maybe GitHub only reads the config from the default branch, so we need to merge it first before seeing any results.

**Comment by jessex** [comment]
@szhu since this includes all of my Auth changes as well, I'm inclined to wait to merge this until after #26.

**Comment by szhu** [comment]
@jessex Sorry, you saw my PR at a bad time :/

I was just testing it to see if it would work! I'm going to remove that commit.

**Comment by szhu** [comment]
@jessex ready for re-review! You can look at the `Files` tab to see this in action!

I will revert the commits that contain the errors prior to merging.

**Pull request merged**
